name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 3.0.0
homepage: https://github.com/aloisdeniel/flutter_sheet_localization

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ">=0.12.0 <0.14.0"
  meta: ^1.3.0
  csv: ^5.0.0
  recase: ^4.0.0-nullsafety.0
  code_builder: ">=3.7.0 <3.8.0"
  dart_style: ">=2.0.0 <2.1.0"
  source_gen: ">=1.0.0 <1.1.0"
  flutter_sheet_localization: ^3.0.0
  build: ">=2.0.0 <2.1.0"
  analyzer: ">=1.4.0 <1.5.0"
  collection: ">=1.15.0 <2.0.0"
  intl: ^0.17.0

dev_dependencies:
  build_test: ^2.0.0
  build_runner: ">=1.12.2 <1.13.0"
